import coreWebVitals from 'eslint-config-next/core-web-vitals'
import typescript from 'eslint-config-next/typescript'

/*
 * eslint-config-next 16 ships native flat configs and exports each one as a
 * plain array on the CommonJS default export. Do not wrap them in FlatCompat
 * (the eslintrc bridge fails with a circular-structure error) and do not use
 * named imports (there are none).
 */
const eslintConfig = [
  ...coreWebVitals,
  ...typescript,
  {
    rules: {
      // CLAUDE.md rule 3: TypeScript strict, no `any`.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    ignores: [
      '.next/',
      'node_modules/',
      'src/app/(payload)/**',
      'src/payload-types.ts',
      'src/payload-generated-schema.ts',
      // Generated by `payload migrate:create`. Never hand-edited, so linting
      // it only produces warnings nobody can act on.
      'src/migrations/**',
    ],
  },
]

export default eslintConfig
