/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    articles: Article;
    events: Event;
    media: Media;
    'contact-submissions': ContactSubmission;
    donations: Donation;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    donations: DonationsSelect<false> | DonationsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'nl' | 'nl'[];
  globals: {
    'site-settings': SiteSetting;
    'anbi-gegevens': AnbiGegeven;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'anbi-gegevens': AnbiGegevensSelect<false> | AnbiGegevensSelect<true>;
  };
  locale: 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * De pagina's van de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Het deel van het webadres na de schuine streep, bijvoorbeeld over-ons. Wordt automatisch ingevuld vanuit de titel. Wijzig dit niet meer zodra de pagina online staat, want bestaande links werken dan niet meer.
   */
  slug: string;
  /**
   * Bouw de pagina op uit blokken. Sleep om de volgorde te wijzigen.
   */
  body?:
    | (
        | {
            heading: string;
            /**
             * Een of twee zinnen onder de kop.
             */
            intro?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Een pad op deze website, zoals /doneren, of een volledig adres.
                   */
                  url: string;
                  style: 'cta' | 'primary' | 'outline';
                  id?: string | null;
                }[]
              | null;
            /**
             * Optioneel. Wordt naast of achter de tekst getoond.
             */
            image?: (number | null) | Media;
            /**
             * De balk onder de banner. Laat leeg om de balk te verbergen. Bijvoorbeeld: 40+ vrijwilligers.
             */
            stats?:
              | {
                  /**
                   * Optioneel. Laat leeg voor een gegeven zonder getal.
                   */
                  value?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Bijvoorbeeld: Onze projecten.
             */
            heading: string;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Waar de link onder de kaart naartoe gaat. Laat leeg voor geen link.
                   */
                  url?: string | null;
                  /**
                   * Bijvoorbeeld: Lees meer.
                   */
                  linkLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredItems';
          }
        | {
            heading: string;
            /**
             * Automatisch toont de eerstvolgende evenementen uit de Agenda. Zo hoeft de homepagina niet apart bijgewerkt te worden.
             */
            source?: ('events' | 'manual') | null;
            limit?: number | null;
            items?:
              | {
                  date: string;
                  title: string;
                  location?: string | null;
                  /**
                   * Klein label rechts, bijvoorbeeld Gratis of € 45. Optioneel.
                   */
                  badge?: string | null;
                  /**
                   * Waar de activiteit naartoe linkt. Optioneel.
                   */
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'agenda';
          }
        | {
            heading: string;
            text?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Een pad op deze website, zoals /doneren, of een volledig adres.
                   */
                  url: string;
                  style: 'cta' | 'primary' | 'outline';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  /**
   * Hoe de pagina getoond wordt in Google en bij het delen op sociale media. Laat leeg om de titel van de pagina te gebruiken.
   */
  meta?: {
    title?: string | null;
    /**
     * Ongeveer 150 tekens.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Afbeeldingen en documenten voor de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijf wat er op de afbeelding te zien is, voor bezoekers die de afbeelding niet kunnen zien. Bij een document: waar het document over gaat.
   */
  alt: string;
  /**
   * Optioneel. Wordt zichtbaar onder de afbeelding getoond.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * De projecten van de stichting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Het deel van het webadres na /projecten/. Wordt automatisch ingevuld vanuit de titel. Wijzig dit niet meer zodra het project online staat.
   */
  slug: string;
  /**
   * Het label op de kaart in het overzicht. Optioneel.
   */
  category?: string | null;
  /**
   * Een of twee zinnen. Wordt getoond op de kaart in het overzicht.
   */
  excerpt?: string | null;
  /**
   * Gebruikt op de kaart en als banner bovenaan de projectpagina.
   */
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * De rij met feiten onder de tekst. Bijvoorbeeld: 8 weken per traject.
   */
  facts?:
    | {
        icon: 'people' | 'duration' | 'location';
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Laat het doelbedrag leeg om de voortgangsbalk te verbergen. De bedragen worden met de hand bijgehouden; zij komen niet automatisch uit de donaties.
   */
  funding?: {
    goal?: number | null;
    raised?: number | null;
  };
  /**
   * De groene balk onderaan de pagina. Laat de kop leeg om hem te verbergen.
   */
  callToAction?: {
    heading?: string | null;
    label?: string | null;
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Nieuwsberichten, artikelen, interviews en verslagen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * Het deel van het webadres na /nieuws/. Wordt automatisch ingevuld vanuit de titel. Wijzig dit niet meer zodra het artikel online staat.
   */
  slug: string;
  /**
   * De datum die bij het artikel staat en waarop het overzicht sorteert. Dit is iets anders dan gepubliceerd zijn.
   */
  publishedAt: string;
  category: 'nieuws' | 'artikel' | 'interview' | 'verslag';
  /**
   * Zet dit artikel bovenaan het overzicht, groot. Is er meer dan één, dan wint het nieuwste.
   */
  featured?: boolean | null;
  /**
   * Wordt getoond als "Door ...". Optioneel.
   */
  author?: string | null;
  /**
   * Een of twee zinnen. Wordt getoond op de kaart in het overzicht.
   */
  excerpt?: string | null;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tags?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Activiteiten en evenementen van de stichting.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Het deel van het webadres na /agenda/. Wordt automatisch ingevuld vanuit de titel.
   */
  slug: string;
  /**
   * Bepaalt of het evenement onder Aankomend of Afgelopen valt.
   */
  startsAt: string;
  /**
   * Optioneel. Zonder eindtijd wordt alleen het begin getoond.
   */
  endsAt?: string | null;
  /**
   * Bijvoorbeeld: De Hal.
   */
  locationName?: string | null;
  /**
   * Wordt gebruikt om op te filteren. Houd de schrijfwijze gelijk.
   */
  city?: string | null;
  /**
   * Wordt gebruikt om op te filteren. Houd de schrijfwijze gelijk.
   */
  theme?: string | null;
  /**
   * Wordt gebruikt om op te filteren. Houd de schrijfwijze gelijk.
   */
  audience?: string | null;
  price?: {
    isFree?: boolean | null;
    amount?: number | null;
  };
  /**
   * Aantal personen. Optioneel.
   */
  capacity?: number | null;
  /**
   * Wordt met de hand bijgehouden; de website neemt geen aanmeldingen aan. Laat leeg om dit niet te tonen.
   */
  spotsAvailable?: number | null;
  /**
   * Waar de knop Aanmelden naartoe gaat. Laat leeg om de knop te verbergen.
   */
  registrationUrl?: string | null;
  excerpt?: string | null;
  image?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Berichten die via het contactformulier zijn binnengekomen. Deze bevatten persoonsgegevens: verwijder ze zodra ze zijn afgehandeld.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * Vink aan zodra iemand op dit bericht heeft gereageerd.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Donaties die via de website zijn gestart. Deze records bevatten persoonsgegevens en zijn niet openbaar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations".
 */
export interface Donation {
  id: number;
  /**
   * Het nummer waarmee deze betaling in het Mollie-dashboard te vinden is.
   */
  molliePaymentId: string;
  amount: number;
  /**
   * Wordt automatisch bijgewerkt door Mollie. Alleen de status "Betaald" betekent dat het geld is ontvangen.
   */
  status: 'open' | 'pending' | 'paid' | 'canceled' | 'expired' | 'failed';
  /**
   * Waar de gever de gift aan wilde besteden. Leeg betekent algemeen.
   */
  fund?: string | null;
  /**
   * Bij een anonieme gift zijn naam en e-mailadres niet opgeslagen.
   */
  anonymous?: boolean | null;
  /**
   * Leeg bij een anonieme gift.
   */
  donorName?: string | null;
  /**
   * Alleen gebruikt om een donatiebevestiging te sturen. Leeg bij een anonieme gift.
   */
  donorEmail?: string | null;
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Accounts voor het beheerpaneel. Beheerders kunnen gebruikers toevoegen en rollen wijzigen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerder: volledige toegang, inclusief gebruikers en instellingen. Redacteur: alleen inhoud bewerken.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'donations';
        value: number | Donation;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              intro?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featuredItems?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    url?: T;
                    linkLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        agenda?:
          | T
          | {
              heading?: T;
              source?: T;
              limit?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    location?: T;
                    badge?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  image?: T;
  body?: T;
  facts?:
    | T
    | {
        icon?: T;
        label?: T;
        id?: T;
      };
  funding?:
    | T
    | {
        goal?: T;
        raised?: T;
      };
  callToAction?:
    | T
    | {
        heading?: T;
        label?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  featured?: T;
  author?: T;
  excerpt?: T;
  image?: T;
  body?: T;
  tags?:
    | T
    | {
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startsAt?: T;
  endsAt?: T;
  locationName?: T;
  city?: T;
  theme?: T;
  audience?: T;
  price?:
    | T
    | {
        isFree?: T;
        amount?: T;
      };
  capacity?: T;
  spotsAvailable?: T;
  registrationUrl?: T;
  excerpt?: T;
  image?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "donations_select".
 */
export interface DonationsSelect<T extends boolean = true> {
  molliePaymentId?: T;
  amount?: T;
  status?: T;
  fund?: T;
  anonymous?: T;
  donorName?: T;
  donorEmail?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Naam, logo, adressen en footer van de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Zoals de naam op de website getoond wordt.
   */
  organisationName: string;
  /**
   * Korte zin onder of naast de naam. Optioneel.
   */
  tagline?: string | null;
  /**
   * Bij voorkeur een SVG of een PNG met transparante achtergrond.
   */
  logo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  /**
   * Bijvoorbeeld: maandag tot en met vrijdag, 9.00 tot 17.00 uur. Eén regel per dag. Optioneel.
   */
  openingHours?: string | null;
  /**
   * De stichting is op meerdere plaatsen actief. Voeg elke locatie toe.
   */
  addresses?:
    | {
        /**
         * Bijvoorbeeld: Tilburg.
         */
        label: string;
        street?: string | null;
        postalCode?: string | null;
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * De links bovenaan elke pagina, in deze volgorde. Sleep om de volgorde te wijzigen.
   */
  mainNavigation?:
    | {
        label: string;
        /**
         * Een pad op deze website, zoals /over-ons.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * De opvallende knop in de kop van de pagina, en op mobiel de balk onderaan het scherm. Laat de tekst leeg om de knop te verbergen.
   */
  headerCta?: {
    label?: string | null;
    url?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Korte tekst over de stichting. Optioneel.
   */
  footerIntro?: string | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Een pad op deze website, zoals /over-ons, of een volledig adres.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * De gegevens die de Belastingdienst verplicht stelt voor een ANBI. Alles op deze pagina is openbaar. Werk de pagina dezelfde dag bij als de statuten, het bestuur, het adres of de activiteiten veranderen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anbi-gegevens".
 */
export interface AnbiGegeven {
  id: number;
  /**
   * De naam zoals die in de statuten en bij de KVK staat.
   */
  statutoryName: string;
  kvkNumber?: string | null;
  rsin?: string | null;
  foundedOn?: string | null;
  /**
   * Bijvoorbeeld: Gemeente Tilburg.
   */
  statutorySeat?: string | null;
  operatingArea?: string | null;
  /**
   * Bijvoorbeeld: 1 januari tot en met 31 december. Vermeld ook het eerste, afwijkende boekjaar.
   */
  fiscalYear?: string | null;
  /**
   * Het post- of bezoekadres is verplicht. Dit mag een postadres zijn en hoeft niet hetzelfde te zijn als het bezoekadres bij Instellingen.
   */
  contact?: {
    address?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  /**
   * Wordt op de pagina getoond bij "Steun ons".
   */
  iban?: string | null;
  /**
   * Zet dit pas op "toegekend" als de beschikking binnen is. Zolang de status is aangevraagd mag de website niet vermelden dat giften aftrekbaar zijn.
   */
  anbiStatus: 'aangevraagd' | 'toegekend';
  /**
   * De datum op de beschikking van de Belastingdienst.
   */
  anbiGrantedOn?: string | null;
  /**
   * Wordt bovenaan de pagina getoond zolang de status is aangevraagd. Vermeld dat de aftrekbaarheid nog niet gegarandeerd is en dat contante giften nooit aftrekbaar zijn.
   */
  statusNotice?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * De doelstelling zoals omschreven in de statuten, met het artikelnummer.
   */
  objective?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Een korte toelichting in gewone taal. Optioneel.
   */
  mission?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Onderdeel van de hoofdlijnen van het beleidsplan. Het volledige beleidsplan hoort niet op de website.
   */
  policyActivities?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  policyIncome?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Vermeld hier ook wat er bij opheffing met een batig saldo gebeurt.
   */
  policyAssets?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Zin waarmee bezoekers het volledige beleidsplan kunnen opvragen.
   */
  policyPlanOnRequest?: string | null;
  /**
   * Voor het bestuur en voor eventueel personeel. Vermeld het ook als bestuursleden onbezoldigd zijn.
   */
  remunerationPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Alleen naam en functie. Woonadres, telefoonnummer en geboortedatum zijn niet verplicht en horen hier niet.
   */
  boardMembers?:
    | {
        role: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bijvoorbeeld over de adviesraad en de commissies. Optioneel.
   */
  boardComposition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Wordt getoond zolang hieronder geen boekjaar is toegevoegd. Vermeld de uiterste publicatiedatum. Een ANBI moet binnen zes maanden na afloop van het boekjaar publiceren; te laat publiceren is de belangrijkste reden dat de status wordt ingetrokken.
   */
  reportingNotice?: string | null;
  /**
   * Per boekjaar het verslag van de activiteiten en de financiële verantwoording: balans, staat van baten en lasten, en de toelichting daarop.
   */
  annualReports?:
    | {
        year: number;
        activityReport?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Balans en staat van baten en lasten, met toelichting.
         */
        financialStatement?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Optioneel en aanvullend. De cijfers moeten ook als gewone tekst op de pagina staan, niet alleen in een PDF.
         */
        documents?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Over doneren, periodieke giften en geoormerkte giften. Claim hier niet dat giften aftrekbaar zijn zolang de ANBI-status niet is toegekend.
   */
  supportText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organisationName?: T;
  tagline?: T;
  logo?: T;
  email?: T;
  phone?: T;
  openingHours?: T;
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        id?: T;
      };
  mainNavigation?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerIntro?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anbi-gegevens_select".
 */
export interface AnbiGegevensSelect<T extends boolean = true> {
  statutoryName?: T;
  kvkNumber?: T;
  rsin?: T;
  foundedOn?: T;
  statutorySeat?: T;
  operatingArea?: T;
  fiscalYear?: T;
  contact?:
    | T
    | {
        address?: T;
        email?: T;
        phone?: T;
      };
  iban?: T;
  anbiStatus?: T;
  anbiGrantedOn?: T;
  statusNotice?: T;
  objective?: T;
  mission?: T;
  policyActivities?: T;
  policyIncome?: T;
  policyAssets?: T;
  policyPlanOnRequest?: T;
  remunerationPolicy?: T;
  boardMembers?:
    | T
    | {
        role?: T;
        name?: T;
        id?: T;
      };
  boardComposition?: T;
  reportingNotice?: T;
  annualReports?:
    | T
    | {
        year?: T;
        activityReport?: T;
        financialStatement?: T;
        documents?: T;
        id?: T;
      };
  supportText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}