/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | 'nl' | 'nl'[];
  globals: {
    'site-settings': SiteSetting;
    'anbi-gegevens': AnbiGegeven;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'anbi-gegevens': AnbiGegevensSelect<false> | AnbiGegevensSelect<true>;
  };
  locale: 'nl';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * De pagina's van de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Het deel van het webadres na de schuine streep, bijvoorbeeld over-ons. Wordt automatisch ingevuld vanuit de titel. Wijzig dit niet meer zodra de pagina online staat, want bestaande links werken dan niet meer.
   */
  slug: string;
  /**
   * Bouw de pagina op uit blokken. Sleep om de volgorde te wijzigen.
   */
  body?:
    | (
        | {
            heading: string;
            /**
             * Een of twee zinnen onder de kop.
             */
            intro?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Een pad op deze website, zoals /doneren, of een volledig adres.
                   */
                  url: string;
                  style: 'cta' | 'primary' | 'outline';
                  id?: string | null;
                }[]
              | null;
            /**
             * Optioneel. Wordt naast of achter de tekst getoond.
             */
            image?: (number | null) | Media;
            /**
             * De balk onder de banner. Laat leeg om de balk te verbergen. Bijvoorbeeld: 40+ vrijwilligers.
             */
            stats?:
              | {
                  /**
                   * Optioneel. Laat leeg voor een gegeven zonder getal.
                   */
                  value?: string | null;
                  label: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            /**
             * Bijvoorbeeld: Onze projecten.
             */
            heading: string;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  image?: (number | null) | Media;
                  /**
                   * Waar de link onder de kaart naartoe gaat. Laat leeg voor geen link.
                   */
                  url?: string | null;
                  /**
                   * Bijvoorbeeld: Lees meer.
                   */
                  linkLabel?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredItems';
          }
        | {
            heading: string;
            items?:
              | {
                  date: string;
                  title: string;
                  location?: string | null;
                  /**
                   * Klein label rechts, bijvoorbeeld Gratis of € 45. Optioneel.
                   */
                  badge?: string | null;
                  /**
                   * Waar de activiteit naartoe linkt. Optioneel.
                   */
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'agenda';
          }
        | {
            heading: string;
            text?: string | null;
            links?:
              | {
                  label: string;
                  /**
                   * Een pad op deze website, zoals /doneren, of een volledig adres.
                   */
                  url: string;
                  style: 'cta' | 'primary' | 'outline';
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  /**
   * Hoe de pagina getoond wordt in Google en bij het delen op sociale media. Laat leeg om de titel van de pagina te gebruiken.
   */
  meta?: {
    title?: string | null;
    /**
     * Ongeveer 150 tekens.
     */
    description?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Afbeeldingen en documenten voor de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijf wat er op de afbeelding te zien is, voor bezoekers die de afbeelding niet kunnen zien. Bij een document: waar het document over gaat.
   */
  alt: string;
  /**
   * Optioneel. Wordt zichtbaar onder de afbeelding getoond.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Berichten die via het contactformulier zijn binnengekomen. Deze bevatten persoonsgegevens: verwijder ze zodra ze zijn afgehandeld.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  message: string;
  /**
   * Vink aan zodra iemand op dit bericht heeft gereageerd.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Accounts voor het beheerpaneel. Beheerders kunnen gebruikers toevoegen en rollen wijzigen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerder: volledige toegang, inclusief gebruikers en instellingen. Redacteur: alleen inhoud bewerken.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              intro?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              image?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        featuredItems?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    url?: T;
                    linkLabel?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        agenda?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    location?: T;
                    badge?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              text?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    style?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Naam, logo, adressen en footer van de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Zoals de naam op de website getoond wordt.
   */
  organisationName: string;
  /**
   * Korte zin onder of naast de naam. Optioneel.
   */
  tagline?: string | null;
  /**
   * Bij voorkeur een SVG of een PNG met transparante achtergrond.
   */
  logo?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  /**
   * Bijvoorbeeld: maandag tot en met vrijdag, 9.00 tot 17.00 uur. Eén regel per dag. Optioneel.
   */
  openingHours?: string | null;
  /**
   * De stichting is op meerdere plaatsen actief. Voeg elke locatie toe.
   */
  addresses?:
    | {
        /**
         * Bijvoorbeeld: Tilburg.
         */
        label: string;
        street?: string | null;
        postalCode?: string | null;
        city: string;
        id?: string | null;
      }[]
    | null;
  /**
   * De links bovenaan elke pagina, in deze volgorde. Sleep om de volgorde te wijzigen.
   */
  mainNavigation?:
    | {
        label: string;
        /**
         * Een pad op deze website, zoals /over-ons.
         */
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * De opvallende knop in de kop van de pagina, en op mobiel de balk onderaan het scherm. Laat de tekst leeg om de knop te verbergen.
   */
  headerCta?: {
    label?: string | null;
    url?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'youtube' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Korte tekst over de stichting. Optioneel.
   */
  footerIntro?: string | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * Een pad op deze website, zoals /over-ons, of een volledig adres.
               */
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * De gegevens die de Belastingdienst verplicht stelt voor een ANBI. Alle velden zijn openbaar op de website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anbi-gegevens".
 */
export interface AnbiGegeven {
  id: number;
  /**
   * De naam zoals die in de statuten en bij de KVK staat.
   */
  statutoryName: string;
  /**
   * Het RSIN of fiscaal nummer van de stichting.
   */
  rsin?: string | null;
  kvkNumber?: string | null;
  /**
   * De contactgegevens zoals geregistreerd bij de KVK. Dit mag een postadres zijn en hoeft niet hetzelfde te zijn als het bezoekadres bij Instellingen.
   */
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  /**
   * De doelstelling van de stichting, zoals omschreven in de statuten.
   */
  objective?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Een samenvatting van het beleidsplan, of het plan in zijn geheel.
   */
  policyPlan?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optioneel. Een PDF met het volledige beleidsplan.
   */
  policyPlanDocument?: (number | null) | Media;
  /**
   * Het beloningsbeleid voor het bestuur en voor eventueel personeel. Vermeld het ook als bestuursleden onbezoldigd zijn.
   */
  remunerationPolicy?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Een korte toelichting op de samenstelling van het bestuur.
   */
  boardComposition?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * De namen en functies van de bestuursleden.
   */
  boardMembers?:
    | {
        name: string;
        /**
         * Bijvoorbeeld: voorzitter, secretaris, penningmeester.
         */
        role: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Per boekjaar het verslag van de activiteiten en de financiële verantwoording. Een ANBI moet deze jaarlijks publiceren.
   */
  annualReports?:
    | {
        year: number;
        activityReport?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        financialStatement?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        /**
         * Optioneel. Bijvoorbeeld de jaarrekening als PDF.
         */
        documents?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  organisationName?: T;
  tagline?: T;
  logo?: T;
  email?: T;
  phone?: T;
  openingHours?: T;
  addresses?:
    | T
    | {
        label?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        id?: T;
      };
  mainNavigation?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  headerCta?:
    | T
    | {
        label?: T;
        url?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  footerIntro?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anbi-gegevens_select".
 */
export interface AnbiGegevensSelect<T extends boolean = true> {
  statutoryName?: T;
  rsin?: T;
  kvkNumber?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  objective?: T;
  policyPlan?: T;
  policyPlanDocument?: T;
  remunerationPolicy?: T;
  boardComposition?: T;
  boardMembers?:
    | T
    | {
        name?: T;
        role?: T;
        id?: T;
      };
  annualReports?:
    | T
    | {
        year?: T;
        activityReport?: T;
        financialStatement?: T;
        documents?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}